// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2tdxCgxEIQ56V5R4asTNyAa3f4X2Ty7M',
    appId: '1:138371306067:web:a06e33ac3ba98a45e0eca6',
    messagingSenderId: '138371306067',
    projectId: 'land-of-evergreen',
    authDomain: 'land-of-evergreen.firebaseapp.com',
    storageBucket: 'land-of-evergreen.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-_Q9szzRbd9-U20bL46a_WkPUy4Ff74',
    appId: '1:138371306067:android:bd9d603bc7820243e0eca6',
    messagingSenderId: '138371306067',
    projectId: 'land-of-evergreen',
    storageBucket: 'land-of-evergreen.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWLgEQxl0mnZri3IiFVfx6McA_1pQflXk',
    appId: '1:138371306067:ios:1ae3eb2a0877aae6e0eca6',
    messagingSenderId: '138371306067',
    projectId: 'land-of-evergreen',
    storageBucket: 'land-of-evergreen.appspot.com',
    iosBundleId: 'com.example.everGreen',
  );
}
